discord:
  id: "1390805997144113244"
  refreshMs: 15000

twitch:
  login: notreallyrx
  clientId: kimne78kx3ncx6brgo4mv6wki5h1ko
  refreshMs: 15000

modules:
  - discord.js
  - twitch.js

socials:
  - label: Github
    url: https://github.com/NotReallyRx
  - label: Youtube
    url: https://youtube.com/@reallynotrx
  - label: Discord
    url: https://discord.com/users/1390805997144113244
  - label: Twitch
    url: https://www.twitch.tv/notreallyrx
