layout:
  scale: 1

discord:
  id: "1390805997144113244"
  refreshMs: 1000

twitch:
  login: notreallyrx
  clientId: kimne78kx3ncx6brgo4mv6wki5h1ko
  refreshMs: 1000

modules:
  - discord.js
  - twitch.js

socials:
  - label: Github
    url: https://github.com/NotReallyRx
  - label: Youtube
    url: https://youtube.com/@reallynotrx
  - label: Discord
    url: https://discord.com/users/1390805997144113244
  - label: Twitch
    url: https://www.twitch.tv/notreallyrx

player:
  title: "Resurrections - Lena Raine"
  src: "https://archive.org/download/official-celeste-original-soundtrack-03-resu-mp-3-128-k/%5BOfficial%5D%20Celeste%20Original%20Soundtrack%20-%2003%20-%20Resu%28MP3_128K%29.mp3"
